Repository nicolegooden/fitlit-kj-ng, pull requests merged in 2020-09, with the labels that each got.

#80 Sleep tests
  src/SleepRepository.js
  test/Sleep-test.js
Labels: documentation, sprint 3

#82 Activity repository kj
  src/ActivityRepository.js
  src/index.html
  src/scripts.js
  test/Activity-test.js
Labels: documentation, sprint 3, sprint 4

#83 Activity implementation ng
  src/ActivityRepository.js
  src/UserRepository.js
  test/Activity-test.js
Labels: documentation, sprint 4

#85 Activity implementation ng
  src/ActivityRepository.js
  src/index.html
  src/scripts.js
  test/Activity-test.js
Labels: Dashboard, documentation, sprint 4

#86 Findweeklydata4test kj
  test/Activity-test.js
Labels: documentation, sprint 4, testing

#88 Readme kj
  README.md
Labels: documentation

#89 Bugs ng
  src/ActivityRepository.js
  src/HydrationRepository.js
  src/SleepRepository.js
  src/index.html
  src/scripts.js
  test/Hydration-test.js
Labels: documentation

#90 Refactor html kj
  README.md
  src/index.html
  src/scripts.js
  src/styles.css
Labels: Dashboard, documentation, enhancement

#91 Finalize kj
  README.md
Labels: documentation
