Repository nicolegooden/fitlit-kj-ng, pull requests merged in 2020-08, with the labels that each got.

#64 User repository ng
  .gitignore
  src/UserRepository.js
  test/UserRepository-test.js
Labels: documentation

#66 User ng
  src/User.js
  src/UserRepository.js
  src/index.html
  src/scripts.js
  src/styles.css
  test/User-test.js
Labels: documentation

#68 Hydration tests kj
  src/Hydration.js
  src/User.js
  src/UserRepository.js
  src/index.html
  src/scripts.js
  test/Hydration-test.js
Labels: documentation

#70 Widget formatting kj
  src/Hydration.js
  src/index.html
  src/scripts.js
  src/styles.css
Labels: Dashboard, documentation

#71 Hydration implementation ng
  package-lock.json
  package.json
  src/HydrationRepository.js
  src/User.js
  src/UserRepository.js
  src/scripts.js
  test/Hydration-test.js
Labels: documentation

#74 Hydration dashboard ng
  package-lock.json
  package.json
  src/HydrationRepository.js
  src/index.html
  src/scripts.js
  src/styles.css
Labels: documentation

#76 Hydration repository kj
  src/HydrationRepository.js
  src/index.html
  src/moment.js
  src/scripts.js
  src/styles.css
  test/Hydration-test.js
Labels: documentation, sprint 2
